### ISSUE TITLE
binderMutex shouldn't have I/O in critical sections

### ISSUE THREAD

**Issue by jonasfj** [Jeffail/leaps#9] opened 2015-10-04 18:31 UTC
We critically should fix the `binderMutex` lock... The critical section covers `NewBinder` which does a `store.Fetch`... This is problematic as people can't join/create documents while we wait for a single document to be loaded...

I looked at it, and I think we should just make an `Abort` method on binder that aborts the loop without saving anything... I just couldn't quiet figure out how to do it... @Jeffail, If you can give a hint on how to make an `Abort()` function that doesn't save the bind, but cleans up all resources, I can do the rest :)
(I'm still a bit new to golang)

With the abort function we can do as follows:
 1) Lock `binderMutex`
 2) Look in `openBinders` for binder
 3) Unlock `binderMutex`
 4) Create binder: `b := NewBinder(...)`
 5) Lock `binderMutex`
 6) If `binder := openBinders[id]` exists, call `b.Abort()`, else set `binder := openBinders[id] = b`
 7) Unlock `binderMutex`
 8) `return binder.Subscribe(...`

Sure, sometime we may create a binder without any clients at the same time as another client creates the same binder... But the binder that is added to `openBinders[id]` is the one both will use, and the other binding will be aborted before any clients are subscribed to it...

**Comment by Jeffail** [comment] 2015-10-04 21:48
Well spotted, been meaning to look at this for a while. `binder.Close()` should close the loop and block until it exits cleanly.

**Comment by jonasfj** [comment] 2015-10-04 21:58
Problem is that `binder.Close()` will `flush` the document, right? Which cases a race...

Hmm... Maybe with the `IsDirty` patch it won't save it anymore, as there are no changes... In that case using `Binder.Close()` should be straight forward.

**Comment by Jeffail** [comment] 2015-10-04 21:59
It will still read the document but it wouldn't have written so we should be fine.

**Comment by lennart** [comment] 2016-06-26 16:57
I get `panic` seemingly random, from L 411 in `binder.go` (slice bounds out of range) which seem somewhat weird, since indices are read from the binder's list of clients that is sliced. I wonder if this is also related to the race condition you talk about, since multiple places change `b.clients` (add or remove) which (althoug I am not sure about this) could lead to the above. 

If I read the source around the panicking line, maybe it would be better to somehow identify the _to be kicked_ client by something else than the volatile indices (I guess they are simply invalid by the time of timeout)

**Comment by Jeffail** [comment] 2016-06-26 17:18
Thanks @lennart, any chance you can paste the full panic dump?

**Comment by lennart** [comment] 2016-06-26 17:41
trying to reproduce (I found a bug in my own code that uses leaps), seems like a false alarm. If I stumble upon this again I'll add the stack trace!

**Comment by lennart** [comment] 2016-06-26 19:39
ok, got it reproduced:

```
		2016-06-26T21:35:57+02:00 | DEBUG | leaps:curator:binder | Received transform:
"{50 0 e 760 0}"
2016-06-26T21:35:57+02:00 | DEBUG | leaps:curator | finding document 1466969178b182c6da-42c6-4ea3-9586-03fc3b59f248, with userID extramuros-server token x
2016-06-26T21:35:57+02:00 | DEBUG | leaps:curator:binder | Subscribed new client extramuros-server
2016/06/26 21:35:57 [doc:read] failed:  timed out
2016-06-26T21:35:57+02:00 | DEBUG | leaps:curator | finding document 1466969178b182c6da-42c6-4ea3-9586-03fc3b59f248, with userID extramuros-server token x
2016/06/26 21:35:57 [doc:read] failed:  timed out
2016-06-26T21:35:57+02:00 | DEBUG | leaps:curator:binder | Subscribed new client extramuros-server
2016-06-26T21:35:58+02:00 | DEBUG | leaps:curator | finding document 1466969178b182c6da-42c6-4ea3-9586-03fc3b59f248, with userID extramuros-server token x
2016/06/26 21:35:58 [doc:read] failed:  timed out
2016-06-26T21:35:58+02:00 | DEBUG | leaps:curator:binder | Kicking client for user: (extramuros-server) for blocked transform send
2016-06-26T21:35:58+02:00 | DEBUG | leaps:curator:binder | Kicking client for user: (extramuros-server) for blocked transform send
panic: runtime error: slice bounds out of range

goroutine 8 [running]:
panic(0x868160, 0xc82000a100)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/lennart/niederschwellig/vendor/github.com/jeffail/leaps/lib/binder.(*impl).processMessage(0xc820106000, 0xc82016a480, 0x0, 0x0, 0xc820252d50, 0x1)
        /home/m/golang/src/github.com/lennart/niederschwellig/vendor/github.com/jeffail/leaps/lib/binder/binder.go:411 +0x894
github.com/lennart/niederschwellig/vendor/github.com/jeffail/leaps/lib/binder.(*impl).loop(0xc820106000)
        /home/m/golang/src/github.com/lennart/niederschwellig/vendor/github.com/jeffail/leaps/lib/binder/binder.go:492 +0xbb3
created by github.com/lennart/niederschwellig/vendor/github.com/jeffail/leaps/lib/binder.New
        /home/m/golang/src/github.com/lennart/niederschwellig/vendor/github.com/jeffail/leaps/lib/binder/binder.go:121 +0x62e
exit status 2
```

The log messages that does not come from leaps is the error message for  the document I wanted to read ([doc:read] failed: timed out). I use a 1second timeout to read, however I also get repeated timeout when reading a document by id (this is with both the Memory and the File backend, maybe this is another issue...)

Seems like the _kick_ handler runs twice at the same time and then fails...

**Comment by Jeffail** [comment] 2016-06-26 20:44
Thanks @lennart, I can see why it's happening, I'll try and push a fix (and some more unit tests) in a few minutes.

**Comment by Jeffail** [comment] 2016-06-26 21:12
@lennart, I've pushed a fix https://github.com/Jeffail/leaps/commit/503384b41af3590959d8257c7b576946577c1f0d.

**Closed** 2017-05-16 19:23 UTC
